### ISSUE TITLE
Subject facet only displays labels for URIs

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital_2#21]

**Comment by terrellt** [comment]
I want to have a discussion about this. In OD1, facets were unique based on URI. Is that really necessary? Does it improve discovery?

I don't think it does. I think the only thing that's important is that when you click the link in the show view to facet that it only returns the ones that match THAT URI.

**Comment by terrellt** [comment]
@OregonDigital/developers @OregonDigital/collaborators @OregonDigital/metadata @OregonDigital/owners Pinging everyone. Thoughts?

**Comment by straleyb** [comment]
Say we didn't have facets unique to URI's, what would the side effect be exactly? Would that add more facets into the list that could be redundant. (E.G one facet is 'Food' and the other is 'food', both the same URI but different facets)

**Comment by terrellt** [comment]
So right now if there are two "Bob Smiths", one with URI http://names.org/Bob and another with URI http://names.org/Bob2, you'd get two facets, that both say "Bob Smith."

I'm saying that instead, we just have one - "Bob Smith"

**Comment by wickr** [comment]
Example in Worktype:

periodicals, from Getty AAT: http://oregondigital.org/catalog/?_=1432335476164&f%5Bdesc_metadata__workType_label_sim%5D%5B%5D=periodicals%24http%3A%2F%2Fvocab.getty.edu%2Faat%2F300026657

Periodicals, from LCSH: http://oregondigital.org/catalog/?_=1432335476165&f%5Bdesc_metadata__workType_label_sim%5D%5B%5D=Periodicals%24http%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects%2Fsh85099890

Periodicals, from LCSH, different URI: http://oregondigital.org/catalog/?_=1432335476172&f%5Bdesc_metadata__workType_label_sim%5D%5B%5D=Periodicals%24http%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects%2Fsh99001647

Periodicals, from LCSH, different URI: http://oregondigital.org/catalog/?_=1432335476172&f%5Bdesc_metadata__workType_label_sim%5D%5B%5D=Periodicals%24http%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects%2Fsh99002086

**Comment by jechols** [comment]
I'm okay with the collapsing of labels for the short-term.  Long-term I think we need a report of some kind that curator-level folks can use to either (a) fix metadata or (b) maybe jam in a better label locally for disambiguation.

**Comment by wickr** [comment]
I think for Names we'd want them to be separated, even if the labels are the same. For subjects, we could maybe get away with collapsing them. For language I don't think it's a problem.

But if you do collapse/combine in the facet list and but then have the differentiated results when you click the URL in the show view, won't you then get the facet results that are differentiated ? I think that might be even more confusing.

I think the following example is a problem: If you browse in Creator facets, see Bob Smith (14), then view the results, click one of them. Instead of going back to the original facet list, in the result show view you click on Bob Smith again, and then that result view has facets on the left for Creator but shows Bob Smith  (9)  because that's differentiated and those all match what you clicked on. How do you know exactly what you're looking at? How do you know the results are different?

**Comment by jechols** [comment]
Names are a problem, but what use is seeing "Bob Smith" five times?  I'd rather figure out a name disambiguation page than try to explain how to get to the right "Bob Smith".

Everything that isn't a name should be collapsed and eventually fixed, I think.

**Comment by straleyb** [comment]
^^^^ I think taking the decision making task away from users is a good idea(having to choose between two facets of the same name but are two totally different URI's) and relying on them refining their search by faceting, would be helpful. But relying on users actually knowing what facets mean could be a problem.

**Comment by straleyb** [comment]
what @jechols was saying, exposing possible issues with the metadata or being able to eventually define better labels is a pretty solid long term goal. But take what I'm saying worth a grain of salt, im still a metadata novice.

**Comment by terrellt** [comment]
I think a good strategy is to collapse and gradually find a better to create more descriptive labels.
