### ISSUE TITLE
Make Hydra::Editor Handle URIs

### ISSUE THREAD

**Issue by terrellt** [OregonDigital/oregondigital_2#31]

**Comment by terrellt** [comment]
If a term has a URI which has a #rdf_label it should display that, you should be able to enter URIs.

**Comment by jechols** [comment]
Success can be defined as, at the least, being able to do the following:

- Visit an edit form and see the Fedora workTypes rather than "default" - the RDF label if available, otherwise URIs
- Update a form that has fedora workTypes and have it properly persist, not store broken workType data

(We'll ditch built-in Fedora data at some point, but at the least it shouldn't break the form to show it)

**Comment by terrellt** [comment]
https://github.com/curationexperts/alexandria-v2/blob/master/app/inputs/controlled_vocabulary_input.rb Take a look at this for one strategy - essentially if what you get from the object is an AT::Resource-like thing then build two fields.

**Comment by terrellt** [comment]
Obsoleted by #78, #80, #82, #83
